Write-Output \"Food Tracker Application Setup Complete!\"
Write-Output \"Project structure created successfully.\"
Write-Output \"\"
Write-Output \"Next steps:\"
Write-Output \"1. Create virtual environment: python -m venv venv\"
Write-Output \"2. Activate virtual environment: .\venv\Scripts\activate\"
Write-Output \"3. Install dependencies: pip install -r requirements.txt\"
Write-Output \"4. Download NLTK data: python -c \\\"import nltk; nltk.download('punkt'); nltk.download('wordnet')\\\"\"
Write-Output \"5. Run the application: python app.py\"
Write-Output \"6. Open browser and go to: http://localhost:5000\"
